version: "3.8"

services:
  php-fpm:
    build:
      context: ./php-fpm
    user: ${USER_ID}:${GROUP_ID}
    environment:
      COMPOSER_CACHE_DIR: /tmp/composer-cache
      YII_DEBUG: true
      YII_ENV: development
    volumes:
      - ../../:/app
      - ./runtime/composer-cache:/tmp/composer-cache

  nginx:
    image: nginx:1.25.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../:/app:ro
      - ./runtime/nginx-log:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/cert:/etc/nginx/cert
    depends_on:
      - php-fpm
